doctrine.dbal.connection_options:
    driver: pdo_mysql
    dbname: azure_php
    host: localhost
    user: root
    password: root
      
doctrine.orm: true

doctrine.orm.entities:
    type: "annotation"
    path: "../library/App/Entity"
    namespace: App\Entity
    
twitter:
    app:
      callbackUrlPath: "/authorize-twitter"
      apiKey: rX6iTo4z7iUZUjbbTjJb9g
      consumerKey: rX6iTo4z7iUZUjbbTjJb9g
      consumerSecret: jHsq24wig8Az2xNdnsr1WJJu0xFrMy3NxGP1MKc87SE
    server:
      requestTokenUrl: "http://twitter.com/oauth/request_token"
      authorizeUrl:    "http://twitter.com/oauth/authorize"
      accessTokenUrl:  "http://twitter.com/oauth/access_token"
      
azure:
  queues:
    atc-main:
      host: "queue.core.windows.net"
      accountName: "atsample"
      accountKey: "NdBuy7sg4SdjpwIsgjgPCqg1dTWOR7oEe76B6S5apvHR4FY+y4vsR+FTeuyrgYvdONAWIVxXS28tqcOe0yI7Cg=="
        